### ISSUE TITLE
Submit button of all the forms is enabled when the input fields are empty

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#11]
![image](https://user-images.githubusercontent.com/97726944/170984565-00c0d001-e299-4e9a-aa3c-fda1a856f3cc.png)
![image](https://user-images.githubusercontent.com/97726944/170984676-d452441a-172c-437b-a953-4cc52882f537.png)

**Comment by devSuneel** [comment]
resolved
