### ISSUE TITLE
Missing buttons from cart drawer

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#13]
The view cart, checkout & continue shopping is missing from cart drawer.
Video: https://www.awesomescreenshot.com/video/9173441?key=40e363636ff67f7d7d65b29a4479c9d9

**Comment by devSuneel** [comment]
resolved

**Comment by Shoaibans** [comment]
The continue shopping link is opening the cart page.
Expected: After clicking on link the cart drawer should close.
Video: 
![image](https://user-images.githubusercontent.com/97726944/171327380-80e4dcfd-e9d4-499f-8e9e-3e5d1161abe0.png)

**Comment by devSuneel** [comment]
resolved

**Comment by Shoaibans** [comment]
Cart drawer removed
