### ISSUE TITLE
Different products in different collection & different name in link

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#30]
The ceramic mugs collection page is having Accent mugs products & In homepage Mugs collection, the link is showing coffee mugs & the page is having different product.
Pls check the video: https://www.awesomescreenshot.com/video/9208729?key=42699568afc77328e2b180b1dea3aad1

**Comment by Shoaibans** [comment]
Not fixed 
Video: https://www.awesomescreenshot.com/video/9214902?key=2b05b13c6eb785366f77ee30ad737f1d

**Comment by devSuneel** [comment]
resolved
