### ISSUE TITLE
Newsletter thank you message

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#32]
The newsletter thank you message is not coming.
Video: https://www.awesomescreenshot.com/video/9209973?key=a8dc11d9953d8aafe0523002a854fe2e

**Comment by devSuneel** [comment]
page is refreshing, this is the theme functionality

**Comment by Shoaibans** [comment]
> page is refreshing, this is the theme functionality

Refreshing is not an issue, but after giving the valid mail in news letter it should give a message Thank You for subscribing or something.
Video: https://www.awesomescreenshot.com/video/9214902?key=2b05b13c6eb785366f77ee30ad737f1d
