### ISSUE TITLE
Product description arrow, spacing between boxes, pricing & review stars in Mac device product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#34]
The arrow is not coming proper & the boxes are coming close and the pricing & review stars are coming small in Mac product page.
![image](https://user-images.githubusercontent.com/97726944/171347075-6517fe8a-8253-4e40-9a76-e12172d455fc.png)

**Comment by ui-abrarul** [comment]
ss
