### ISSUE TITLE
Missing instafeed from preview

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#38]
Live: https://teesfromdees.com/
![image](https://user-images.githubusercontent.com/97726944/177253986-6927b103-f1db-4cc6-ab79-d84821e2b918.png)

Preview: https://2zsx2i1hp1qvdg6t-59638743228.shopifypreview.com/
![image](https://user-images.githubusercontent.com/97726944/177254028-e612d0b5-20db-4a43-8a92-1da60914ff72.png)

**Comment by stores-cedcommerce** [comment]
Not a issue it keep s changing as per the updates in Instagram.
