### ISSUE TITLE
Accessories collection page banner is not loading in preview

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#40]
Live: https://teesfromdees.com/collections/accessories
![image](https://user-images.githubusercontent.com/97726944/177260413-3cb569e4-0243-4fa8-9f32-ccc0943377ed.png)

Preview: https://2zsx2i1hp1qvdg6t-59638743228.shopifypreview.com/collections/accessories
![image](https://user-images.githubusercontent.com/97726944/177260308-8ad0163b-950e-440b-8572-edb55ad99f9b.png)

**Comment by stores-cedcommerce** [comment]
Done
