### ISSUE TITLE
Different products in New Arrivals section in Homepage

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#41]
Live:
![image](https://user-images.githubusercontent.com/97726944/177296015-ab942322-959b-4e58-8509-8d8fd10b6487.png)

Preview: 
![image](https://user-images.githubusercontent.com/97726944/177296133-f19defbf-2918-40b2-834d-98997469e160.png)

**Comment by stores-cedcommerce** [comment]
Not an issue
