### ISSUE TITLE
Variation in banner images in mobile

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#44]
The banner images are looking small in preview
Live: https://teesfromdees.com/
![image](https://user-images.githubusercontent.com/97726944/177299746-878be06e-5a24-4ec4-8bd8-f7315361665e.png)
![image](https://user-images.githubusercontent.com/97726944/177299841-0f23fbbf-a5bd-4c35-9094-0d87f577f9a3.png)

Preview: https://2zsx2i1hp1qvdg6t-59638743228.shopifypreview.com/
![image](https://user-images.githubusercontent.com/97726944/177299932-d346265f-d7d2-443b-ab40-7bb6be74b100.png)
![image](https://user-images.githubusercontent.com/97726944/177300015-2d2c6971-5f91-46d6-8f48-14398b83e538.png)

**Comment by stores-cedcommerce** [comment]
Not an issue
