### ISSUE TITLE
Missing banner from collections/all page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#46]
Live: https://teesfromdees.com/collections/all
![image](https://user-images.githubusercontent.com/97726944/177301135-c2d7172c-5e43-445c-a575-4011b16e8316.png)

Preview: https://2zsx2i1hp1qvdg6t-59638743228.shopifypreview.com/collections/all
![image](https://user-images.githubusercontent.com/97726944/177301273-9532bfb0-91e8-4ef9-a508-636988c0337a.png)

**Comment by stores-cedcommerce** [comment]
Done
