### ISSUE TITLE
Low speed in mobile 

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#47]
Homepage:
![image](https://user-images.githubusercontent.com/97726944/177304400-ec4efcae-4836-4333-9780-8af53c5f102b.png)

Collection: 
![image](https://user-images.githubusercontent.com/97726944/177304747-489dc7c7-d89d-4f93-aaf5-32eefb5b5d91.png)

Product: 
![image](https://user-images.githubusercontent.com/97726944/177304941-7764db53-08f6-4d9d-b163-0946752ebb99.png)

Cart: 
![image](https://user-images.githubusercontent.com/97726944/177305516-c94e092b-d78e-4ebb-8433-985471b84a01.png)

**Comment by stores-cedcommerce** [comment]
Not an issue. we don;t work on cart page and this is the final speed as the speed is not increasing
