### ISSUE TITLE
Missing swatches color

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#5]
For some of the products, the swatches color is not coming.
https://2dkbddoshuxba53x-59638743228.shopifypreview.com/collections/hoodies/products/thankful-grateful-blessed-unisex-heavy-blend%E2%84%A2-hooded-sweatshirt
![image](https://user-images.githubusercontent.com/97726944/170982386-9280448a-35b2-4353-8fd3-cbb3407506f2.png)

**Comment by Shoaibans** [comment]
There is a console error 
![image](https://user-images.githubusercontent.com/97726944/171330671-be57ad9f-4341-43bf-9b89-7c5b92aa377f.png)
The error is not coming on the live site
![image](https://user-images.githubusercontent.com/97726944/171330863-f1dd209f-76f5-4bf5-8f09-971bc72827e8.png)

**Comment by devSuneel** [comment]
![Uploading Screenshot from 2022-06-01 15-05-40.png…]()

**Comment by devSuneel** [comment]
resolved
