### ISSUE TITLE
Email is not clickable in contact page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#6]
![image](https://user-images.githubusercontent.com/97726944/170982805-17782184-14a8-4d09-97f1-8f1245fa1c2a.png)

**Comment by Shoaibans** [comment]
On clicking the mail, we are redirecting to the page not found.
Video: https://www.awesomescreenshot.com/video/9207872?key=a4faab0f198d6723d0d4c897c70c56f3

**Comment by devSuneel** [comment]
resolved
